### ISSUE TITLE
Mosaik.Core source missing?

### ISSUE THREAD

**Issue by kameko** [curiosity-ai/catalyst#38]
When I click the [source repository](https://github.com/curiosity-ai/mosaik-core) link for the NuGet package [www.nuget.org/packages/Mosaik.Core/](https://www.nuget.org/packages/Mosaik.Core/), which Catalyst depends on, the repository is missing. Did it move? I'm not sure what Mosaik.Core even does, but it's kind of a big problem if one of the dependencies for this project just dropped off the face of the earth. I tried using NuGet's feature to contact the package owner, but I got no response.

**Comment by theolivenbaum** [comment]
Hi @kameko 

The NuGet package dependency is some internal code we use that didn't make sense to be included on Catalyst, but that (pending some strategic refactoring), is still a dependency for it. You can reverse engineer if you want to make sure what is on it. Strange regarding the contact feature - will double check what's published there - as it is our package after all.

It is in our roadmap to fully remove this dependency, but as this also affects our internal code-base, we've to do it carefully not to break anything. In any case, rest assured that the NuGet package **will not** (it's our package after all, and obviously as users of Catalyst we also depend on it) and **cannot** go away (this is by design with NuGet packages - once published they can never be "unpublished", only hidden from search).

Cheers,

Rafael
