### ISSUE TITLE
Add a quick Dependency Parsing example to the readme.

### ISSUE THREAD

**Issue by cdibbs** [curiosity-ai/catalyst#44]
**Is your feature request related to a problem? Please describe.**

I am having trouble figuring out how dependency parsing works. I found the `AveragePerceptronDependencyParser` and added it to the NLP pipeline after instantiating it with `FromStoreAsync(Language.English, Version.Latest, "")` but I don't know how to access its output. In particular, the `DependencyType` property on `IToken` looked promising, but always seemed to be the empty string.

**Describe the solution you'd like**

It would be nice to see a couple of quick examples for how to work with it such as extracting the root verb, subject, and object of a sentence.

**Describe alternatives you've considered**

**Additional context**
```c#
Storage.Current = new OnlineRepositoryStorage(new DiskStorage("catalyst-models"));
var nlp = await Pipeline.ForAsync(Language.English);
var doc = new Document("The quick brown fox jumps over the lazy dog", Language.English);
nlp.Add(await AveragePerceptronDependencyParser.FromStoreAsync(Language.English, Version.Latest, ""));
nlp.ProcessSingle(doc);
```

Thanks for your work on what looks like a very promising library!

**Comment by ProductiveRage** [comment]
This might be more simplistic than you are looking for if you're looking at the AveragePerceptronDependencyParser and wanting to extract a single root verb but you can tag the tokens in a document with a part-of-speech type like this:

```
Storage.Current = new OnlineRepositoryStorage(new DiskStorage("catalyst-models"));
var document = new Document("The quick brown fox jumps over the lazy dog", Language.English);
var nlp = await Pipeline.ForAsync(Language.English);
nlp.ProcessSingle(document);
foreach (var sentence in document)
{
    foreach (var word in sentence)
    {
        Console.WriteLine(word.POS + "\t" + word.Value);
    }
}
```

The output from the above code is this:

```
DET     The
ADJ     quick
ADJ     brown
NOUN    fox
VERB    jumps
ADP     over
DET     the
ADJ     lazy
NOUN    dog
```

(The `PartOfSpeech` enum values - DET, ADJ, etc.. - match the standard abbreviations that you will see used elsewhere, such as this "[Part of Speech Tagging](https://polyglot.readthedocs.io/en/latest/POS.html)" from the tutorial of another NLP library).

**Comment by cdibbs** [comment]
@ProductiveRage I appreciate the well-written tips, but you are correct that I need that dependency structure to extract "dobj", "nsubj", and the like.

If this library doesn't quite support that, yet, I could do some educated guessing with simpler sentences in which earlier nouns and pronouns are more likely to be the subject. I'd rather not, though. Another option would be to finagle Python's SpaCy library via Python.NET, but that sounds brittle at best.

**Comment by theolivenbaum** [comment]
Hi @cdibbs  - 

Just checked quickly - it's strange that the value was supposed to be copied back to the token using [this method](https://github.com/curiosity-ai/catalyst/blob/42e75d4c4a1405c2510260afc9ef1fa94cbebf9b/Catalyst/src/Models/Base/AveragePerceptronDependencyParser.cs#L940), which ends up calling the [methods here](https://github.com/curiosity-ai/catalyst/blob/7384cbcf044e3a1bcf4bf51babc0a6193eba8797/Catalyst/src/Base/Document.cs#L131) to store the values into the Document data store.

So I stumbled on [this line](https://github.com/curiosity-ai/catalyst/blob/42e75d4c4a1405c2510260afc9ef1fa94cbebf9b/Catalyst/src/Models/Base/AveragePerceptronDependencyParser.cs#L622) - and then the issue is obvious 🤦‍♂️ 

It seems like the code to train the dependency parser was just not finished, and it was not storing the label names. I'll fix it and retrain the models - will update the issue when that's done.

You might need to delete the model cache locally to reflect it.

**Comment by cdibbs** [comment]
@theolivenbaum I wouldn't mind giving it a try. I don't have much experience, though, and I am not sure where the training data is. Is that publicly available somewhere? Thanks!
